### ISSUE TITLE
open() method deprecated?

### ISSUE THREAD

**Issue by anandpatel010** [RiseVision/rise-py#5]
I want to open an account in python.

It seems the open() method is deprecated, is there a replacement or has it been removed?

**Comment by anandpatel010** [comment]
also, the send() method also says its deprecated

**Comment by roosmaa** [comment]
Yes, both of them have been deprecated (on the node side). I took over maintainership of this library last week, and I haven't gotten around to implementing alternatives.

The old way of doing things was to send the secret to the node and the node would generate the correct transaction. This was somewhat acceptable for nodes running on the same machine. However, it isn't at all acceptable for nodes that are running on another machine (due to security concerns). With the node typescript rewrite all of such APIs were deprecated.

The new approach is to sign the transactions directly on the caller side, that way the account secret is never exposed to the network.

If you aren't tied to Python, then for the time being you can look into the javascript/typescript libraries. There you can use the [dpos-offline](https://github.com/vekexasia/dpos-offline) package to do the offline signing.

**Comment by anandpatel010** [comment]
Ah, I completely agree with the reason you chose to remove those methods... I don't need to use the methods now but I'm interested in how to sign Rise tx/s on the client side.

**Comment by roosmaa** [comment]
Ok, a new version of risesdk has been published. It now supports signing transactions locally and all the deprecated REST API methods have been removed. The _examples/_ folder has usage examples. Closing this issue now.
